name: Trigger Supabase Reset Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Her dakika

jobs:
  call-reset-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        run: |
          curl -X POST https://fgefubfhzrkibyglnilu.functions.supabase.co/reset-stock \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"

            # workflow refresh
